name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-NODE-14-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn
      - name: Alex
        run: yarn alex
      - name: Run ESLint
        run: yarn lint
      - name: Run tests
        run: yarn test:ci
